web:
    build: .
    volumes:
        - .:/code
    links:
        - redis
    expose:
        - "5000"
redis:
    image: hypriot/rpi-redis
lb:
    image: clemenshemmerling/tutum-haproxy
    links:
        - web
    ports:
        - "80:80"
    environment:
        - BACKEND_PORT=5000
        - BALANCE=roundrobin

